name: deploy changes on webserver
on:
  push: 
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: justin.pakj.dev
        username: kennedjustin7
        key: ${{ secrets.SSH_KEY }}
        #script_path: ./DnDSheets/scripts/rebuild.sh
        script: |
          cd /home/kennedjustin7/DnDSheets
          git pull
          /home/kennedjustin7/.bun/bin/bun i
          /home/kennedjustin7/.bun/bin/bun pm trust --all
          /home/kennedjustin7/.bun/bin/bun vite build
          sudo systemctl restart dnd-site
