name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: bun i
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        PW_TEST_USERNAME: ${{ secrets.pw_username }}
        PW_TEST_PASSWORD: ${{ secrets.pw_password }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
